#pragma once

#include <pgmspace.h>

const char INDEX_HTML[] PROGMEM =
"<!DOCTYPE html><html><head><meta charset=UTF-8>"
"<meta name=viewport content=\"width=device-width,initial-scale=1\">"
"<title>ESP32</title><style>"
"body{margin:0;font:14px sans-serif;background:#eee;padding:12px}"
".s{max-width:680px;margin:0 auto;background:#fff;border:1px solid #ccc;border-radius:6px;padding:12px}"
"h1{margin:0 0 4px;font-size:1.4rem}"
"p{margin:0;color:#666;font-size:.85rem}"
"#st{margin-top:10px;font-weight:700;color:#c00}"
"#st.ok{color:#060}"
".g{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}"
".c{border:1px solid #ccc;border-radius:4px;padding:10px}"
".l{font-size:.7rem;text-transform:uppercase;letter-spacing:.05em;color:#888}"
".v{font-size:1.8rem;font-weight:700;color:#c00;margin-top:4px}"
"#m{margin-top:10px;font-size:.8rem;color:#666}"
"</style></head><body>"
"<div class=s><h1>ESP32 Telemetry</h1><p>Current and chip temp.</p>"
"<div id=st>Connecting...</div>"
"<div class=g>"
"<div class=c><div class=l>Current</div><div id=cur class=v>--</div></div>"
"<div class=c><div class=l>Chip Temp</div><div id=tmp class=v>--</div></div>"
"</div><div id=m>Waiting...</div></div>"
"<script>"
"var g=function(i){return document.getElementById(i)},"
"s=g('st'),c=g('cur'),t=g('tmp'),m=g('m'),"
"ss=function(x,ok){s.textContent=x;s.className=ok?'ok':''};"
"var ev=new EventSource('/events');"
"ev.addEventListener('open',function(){ss('Connected',1)});"
"ev.addEventListener('status',function(){ss('Connected',1)});"
"ev.addEventListener('telemetry',function(e){"
"var d;try{d=JSON.parse(e.data)}catch(_){return}"
"c.textContent=typeof d.c=='number'?d.c.toFixed(2)+' A':'--';"
"t.textContent=typeof d.t=='number'?d.t.toFixed(1)+'\xB0'+'C':'--';"
"m.textContent=d.sat?'ADC sat':'OK'"
"});ev.onerror=function(){ss('Reconnecting...',0)}"
"</script></body></html>";
